name: Build Portable Linux Executable

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - master
      - main

jobs:
  build:
    # También esta ubuntu-latest
    # Using ubuntu-22.04 to balance glibc compatibility with GitHub's supported runners
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      # Linux environments often need C-compilers and headers to build 
      # Python cryptography libraries from scratch.
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libffi-dev libssl-dev

    - name: Install Python Dependencies and PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Executable
      run: |
        # Change directory into the Linux folder where laZagne.py actually lives
        cd Linux
        pyinstaller --onefile laZagne.py 

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LaZagne-Linux-Binary
        # The finished binary will be in the 'dist' folder inside the Linux directory
        path: Linux/dist/laZagne
