name: Build LaZagne Executable

on:
  workflow_dispatch:  # Allows you to trigger the build manually
  push:
    branches:
      - master        # Triggers automatically if you update the master branch
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies and PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Executable
      run: |
        cd Windows
        pyinstaller lazagne.spec

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LaZagne-Windows-EXE
        path: Windows/dist/lazagne.exe
